# Generated by Django 2.1.3 on 2018-11-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('estadoCivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.EstadoCivil')),
            ],
        ),
    ]
